config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "public/index"
  root to: "conversations#index"
  resources :conversations, only: [:show, :index]

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	has_many :messages
	has_many :participants
	has_many :users, through: :participants

	validates_uniqueness_of :name
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :user
	belongs_to :conversation
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages
	has_many :participants
	has_many :conversations, through: :participants

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper

  before_action :check_user

  def initialize_session
    puts "Session Initialized\n"
  end

  def system_msg(ev, msg)
    broadcast_message ev, { 
      user_name: current_user.email, 
      received: Time.now.to_s(:short), 
      msg_body: msg[:msg_body]
    }
  end

  def private_msg(ev, msg)
    channel = msg[:channel_name].to_sym
    WebsocketRails[channel].trigger(ev, {
        user_name: current_user.email,
        received: Time.now.to_s(:short),
        msg_body: msg[:msg_body]
      })
  end

  def new_message
		private_msg :new_message, message
  	puts "new message: #{message}" 
  end

  def client_connected
    private_msg :new_message, "client #{client_id} connected"
    puts "private client #{client_id} connected"
  end

  def delete_user
    connection_store[:user] = nil
    private_msg "client #{client_id} disconnected"
    broadcast_user_list
  end

  private
    def check_user
      @conversation = Conversation.where(name: message[:channel_name]).first
      unless @conversation.users.include? current_user
        puts 'unautherized'
        render :nothing => true, :status => 401
      end
    end
end

app/controllers/conversations_controller.rb
class	ConversationsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_user, only: [:show]

	def index
		@conversations = current_user.conversations
	end

	def show
		@conversation = Conversation.find(params[:id])
		@messages = @conversation.messages
	end

	private
		def check_user
			@conversation = Conversation.find(params[:id])
			unless @conversation.users.include?(current_user)
				render :nothing => true, :status => 401
			end
		end
end

app/controllers/public_controller.rb
class	PublicController < ApplicationController
	before_action :authenticate_user!
	
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<ul>
	<% @conversations.each do |conversation| %>
		<li> <%= link_to conversation.name, conversation_path(conversation.id) %> </li>
	<% end %>
</ul>

app/views/conversations/show.html.erb
<div id="chat" class="well" data-uri="<%= request.host %>:<%= request.port %>/websocket" data-channel="<%= @conversation.name %>">
	
</div>

<div class="form-inline well">
  <fieldset>
    <input type="text" class="input-xlarge" id="message">
    <button id="send" class="btn btn-primary">Send</button>
  </fieldset>
</div>

<script type="text/javascript">
	jQuery(function() {
		var dispatcher = new WebSocketRails($('#chat').data('uri'), true);
		var private_channel = dispatcher.subscribe($('#chat').data('channel'));

		var messageQueue = [];

		private_channel.on_success = function(data) {
			console.log('channel success: ' + data.message);
		}

		dispatcher.on_open = function(data) {
			console.log('Connection has been established: ', data);
		}

		private_channel.bind('new_message', function(message) {
	    console.log('new message: ' + message.msg_body + ', ' + message.user_name + ', ' + message.received);
	    newMessage(message);
	  });

	  $('#send').bind('click', function() {
	    // console.log('clicked!!');
	    sendMessage();
	  })

	  function sendMessage() {
	    message = $('#message').val();
	    user_name = $('#user_name').val();
	    dispatcher.trigger ('new_message', {user_name: user_name, msg_body: message, channel_name: $('#chat').data('channel')});
	    $('#message').val('');
	  }

	  function messageTemplate(message) {
	    return "<div class='message' ><label class='label label-info'>[" + message.received + "] " + message.user_name +"</label>&nbsp;: "+ message.msg_body +"</div>";
	  }

	  function shifMessageQueue() {
	    messageQueue.shift();
	    $('#chat div.messages:first').slideDown(100, function() {
	      $(this).remove();
	    });
	  }

	  function newMessage(message) {
	    messageQueue.push(message);
	    if (messageQueue.length > 15) {
	      shiftMessageQueue();
	    }
	    appendMessage(message);
	  }

	  function appendMessage(message) {
	    var template = messageTemplate(message);
	    $('#chat').append(template);
	    //template.slideDown(140);
	  }

	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ws1Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
	<strong>signed in as <%= current_user.email %></strong>
	<%= link_to "sing out", destroy_user_session_path, method: :delete  %>
<% else %>
	<%= link_to "sing in", new_user_session_path  %>
	<%= link_to "sing up", new_user_registration_path %>
<% end %> <!-- if -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>